# 数据库表对应的 Python 字典
TABLES = {
    'hotel': {
        'id': 'INT PRIMARY KEY AUTO_INCREMENT',
        'version': 'VARCHAR(30)',
        'hotelcode': 'VARCHAR(45)',
        'name': 'VARCHAR(100)',
        'groupcode': 'VARCHAR(45)',
        'brandcode': 'VARCHAR(45)',
        'groupname': 'VARCHAR(100)',
        'brandname': 'VARCHAR(100)',
        'enname': 'VARCHAR(100)',
        'country': 'VARCHAR(45)',
        'province': 'VARCHAR(45)',
        'city': 'VARCHAR(45)',
        'minpoints': 'INT',
        'minprice': 'INT',
        'pointvalue': 'INT',
        'creditcarddiscount': 'INT',
        'hotscore': 'INT',
        'score': 'INT',
        'latitude': 'DECIMAL(10,5)',
        'longitude': 'DECIMAL(10,5)',
        'address': 'VARCHAR(200)',
        'startyear': 'DATE',
        'decoyear': 'DATE',
        'features': 'VARCHAR(100)',
        'createtime': 'TIMESTAMP'
    },
    'hotelbrand': {
        'id': 'INT PRIMARY KEY AUTO_INCREMENT',
        'version': 'VARCHAR(30)',
        'brandcode': 'VARCHAR(45)',
        'name': 'VARCHAR(100)',
        'enname': 'VARCHAR(100)',
        'logo': 'VARCHAR(200)',
        'createtime': 'TIMESTAMP'
    },
    'hotelgroup': {
        'id': 'INT PRIMARY KEY AUTO_INCREMENT',
        'version': 'VARCHAR(30)',
        'groupcode': 'VARCHAR(45)',
        'name': 'VARCHAR(100)',
        'enname': 'VARCHAR(100)',
        'logo': 'VARCHAR(200)',
        'createtime': 'TIMESTAMP'
    },
    'hotelprice': {
        'id': 'INT PRIMARY KEY',
        'version': 'VARCHAR(30)',
        'groupcode': 'VARCHAR(45)',
        'brandcode': 'VARCHAR(45)',
        'hotelcode': 'VARCHAR(45)',
        'name': 'VARCHAR(100)',
        'price': 'INT',
        'minprice': 'INT',
        'minpoints': 'INT',
        'pricedate': 'DATE',
        'createtime': 'TIMESTAMP'
    },
    'loadboard': {
        'id': 'INT PRIMARY KEY AUTO_INCREMENT',
        'version': 'VARCHAR(30)',
        'country': 'VARCHAR(45)',
        'province': 'VARCHAR(45)',
        'city': 'VARCHAR(45)',
        'name': 'VARCHAR(45)',
        'status': 'TINYINT',
        'createtime': 'TIMESTAMP',
        'updatetime': 'TIMESTAMP'
    },
    'usr': {
        'id': 'INT PRIMARY KEY AUTO_INCREMENT',
        'openid': 'VARCHAR(45)',
        'name': 'VARCHAR(45)',
        'nickname': 'VARCHAR(45)',
        'gender': 'CHAR(1)',
        'mobileno': 'VARCHAR(45)',
        'wechatid': 'VARCHAR(45)',
        'email': 'VARCHAR(45)',
        'point': 'INT',
        'province': 'VARCHAR(45)',
        'city': 'VARCHAR(45)',
        'address': 'VARCHAR(45)',
        'natio': 'VARCHAR(45)',
        'birthdate': 'VARCHAR(45)',
        'idno': 'VARCHAR(45)',
        'idcardfront': 'VARCHAR(45)',
        'idcardback': 'VARCHAR(45)',
        'idcardenddate': 'VARCHAR(45)',
        'avatar': 'VARCHAR(200)',
        'portrait': 'VARCHAR(200)',
        'createtime': 'TIMESTAMP',
        'updatetime': 'TIMESTAMP',
        'active': 'TINYINT',
        'inactivereason': 'VARCHAR(45)',
        'inactivetime': 'TIMESTAMP',
        'inactiveby': 'VARCHAR(45)',
        'activetime': 'TIMESTAMP',
        'activeby': 'VARCHAR(45)',
        'verified': 'TINYINT',
        'verifiedtime': 'TIMESTAMP',
        'verifiedby': 'VARCHAR(45)',
        'agreecontract': 'TINYINT',
        'agreetime': 'TIMESTAMP',
        'faceverified': 'TINYINT',
        'faceverifiedtime': 'TIMESTAMP',
        'faceverifycount': 'INT',
        'facelastverifytrytime': 'TIMESTAMP',
        'facetodaytrycount': 'INT',
        'note': 'VARCHAR(80)'
    }
}